[package]
name = "podchecker"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
shuttle-runtime = "0.18.0"
axum = "0.6.18"
shuttle-axum = "0.18.0"
tokio = "1.28.2"
reqwest = "0.11.8"
xml = "0.8.10"
thiserror = "1.0.40"
anyhow = "1.0.71"
